### ISSUE TITLE
[BUG] Cannot find module 'prettier-plugin-tailwindcss'

### ISSUE THREAD

**Issue by andershagbard** [creyD/prettier_action#111]
The following workflow gives this error:
```
...
Installing prettier...
Checking plugin: prettier-plugin-tailwindcss
Checking plugin: @shopify/prettier-plugin-liquid
Prettifying files...
Files:
Error:  Cannot find module 'prettier-plugin-tailwindcss'
Error:  Require stack:
Error:  - /runner/_work/_actions/creyD/prettier_action/v4.2/node_modules/prettier/index.js
Error:  - /runner/_work/_actions/creyD/prettier_action/v4.2/node_modules/prettier/cli.js
Error:  - /runner/_work/_actions/creyD/prettier_action/v4.2/node_modules/prettier/bin-prettier.js
Problem running prettier with --write .
Error: Process completed with exit code 1.
```

Workflow
```yaml
name: Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-prettier:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_plugins: "prettier-plugin-tailwindcss @shopify/prettier-plugin-liquid"
          prettier_options: --write .
          only_changed: True
```

.prettierrc.json
```json
{
  "printWidth": 100,
  "singleQuote": true,
  "plugins": ["prettier-plugin-tailwindcss"],
  "overrides": [
    {
      "files": ["**/*.liquid"],
      "options": {
        "singleQuote": false
      }
    }
  ]
}
```

Not sure how to proceed.

**Comment by karkir0003** [comment]
@creyD What would be the ETA on having this bug resolved. My dev team's project uses your action as part of our build checks

**Comment by creyD** [comment]
@karkir0003 Can you please try with version 4.3?

**Comment by karkir0003** [comment]
It seems like using version 4.3 works @creyD. I'll keep you posted if another error comes up

**Comment by creyD** [comment]
Good, @andershagbard Please confirm that it works with 4.3 for you too.

**Comment by andershagbard** [comment]
Same error `Cannot find module 'prettier-plugin-tailwindcss'`

**Comment by timsu92** [comment]
Feels like the problem is this:
https://github.com/creyD/prettier_action/blob/31355f8eef017f8aeba2e0bc09d8502b13dbbad1/entrypoint.sh#L62-L65

**Comment by jakeboone02** [comment]
> Feels like the problem is this:
> 
> https://github.com/creyD/prettier_action/blob/31355f8eef017f8aeba2e0bc09d8502b13dbbad1/entrypoint.sh#L62-L65

@timsu92 I don't think that's the issue. `"prettier-plugin-tailwindcss"` matches that regex, and that's not the error message being presented anyway.

I'm seeing the same issue with v4.3: `'Cannot find module 'prettier-plugin-organize-imports'`.

[Latest CI job results here](https://github.com/react-querybuilder/react-querybuilder/actions/runs/4549374268/jobs/8021383202?pr=493).

[Config](https://github.com/react-querybuilder/react-querybuilder/blob/1382af447152ff6c40fe5c1121afe96d077f6280/.github/workflows/prettier.yml):

```yml
name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check *.{mj,t}s examples/**/* packages/*/src/** packages/*/dev/** packages/react-querybuilder/genericTests/** website/*.js website/{docs,src,versioned_docs,versioned_sidebars}/**
          prettier_plugins: 'prettier-plugin-organize-imports'
      - name: Git diff
        if: ${{ failure() }}
        run: git diff && exit 1
```

**Comment by creyD** [comment]
@jakeboone02 Any ideas on how to fix this?

**Comment by jakeboone02** [comment]
@creyD I'm not sure if this will help, but I had a similar issue when trying to use Prettier's JavaScript API from [Bun](https://bun.sh/). The solution to that particular problem was to specify the location of the `/node_modules` directory with the `pluginSearchDirs` option (`--plugin-search-dir` on the command line). Seemed unnecessary but, like I said, it resolved the issue.

**Comment by callumnewlands** [comment]
Is there any update on this? I'm having the same issue using `creyD/prettier_action@master` (v4.3) with `"prettier": "3.0.2"` and `"prettier-plugin-tailwindcss": "0.5.3"`

The possible fix proposed by [@jakeboone02](https://github.com/jakeboone02) doesn't seem to work due to `--plugin-search-dir` being [removed in Prettier 3.0](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker)

Error Log:
```sh
Run creyD/prettier_action@master
  with:
    prettier_options: --write {**/*,*}.{js,jsx,mjs,cjs,ts,tsx,css,scss,sass}
    file_pattern: src
    prettier_plugins: prettier-plugin-tailwindcss
    commit_message: Prettified Code!
    same_commit: false
    dry: false
    prettier_version: false
    working_directory: false
    only_changed: false
    github_token: ***
    clean_node_folder: true
Run PATH=$GITHUB_ACTION_PATH/node_modules/.bin:$PATH /home/runner/work/_actions/creyD/prettier_action/master/entrypoint.sh
  PATH=$GITHUB_ACTION_PATH/node_modules/.bin:$PATH /home/runner/work/_actions/creyD/prettier_action/master/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_COMMIT_MESSAGE: Prettified Code!
    INPUT_COMMIT_DESCRIPTION: 
    INPUT_SAME_COMMIT: false
    INPUT_COMMIT_OPTIONS: 
    INPUT_FILE_PATTERN: src
    INPUT_PRETTIER_OPTIONS: --write {**/*,*}.{js,jsx,mjs,cjs,ts,tsx,css,scss,sass}
    INPUT_DRY: false
    INPUT_PRETTIER_VERSION: false
    INPUT_ONLY_CHANGED: false
    INPUT_PRETTIER_PLUGINS: prettier-plugin-tailwindcss
    INPUT_WORKING_DIRECTORY: false
    INPUT_GITHUB_TOKEN: ***
    INPUT_CLEAN_NODE_FOLDER: true
Installing prettier...
Checking plugin: prettier-plugin-tailwindcss
Prettifying files...
Files:
Error:  Cannot find package 'prettier-plugin-tailwindcss' imported from /home/runner/work/repo_name/repo_name/noop.js
Problem running prettier with --write {**/*,*}.{js,jsx,mjs,cjs,ts,tsx,css,scss,sass}
Error: Process completed with exit code 1.
```

**Comment by callumnewlands** [comment]
I was having this same issue with `prettier_action v4.3` (and the config files shown below) and was able to work around it by adding an `npm install` step before calling the action to instal the plugin to the runner rather than relying on the action to do it which seems to get it to work -- not sure if that helps with debugging this or helps anyone else work around it?

Here's my (now) working workflow file for reference
```yml
...
jobs:
  build-and-test:
    name: 'Build, Format and Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm i

      - name: Run Prettier
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: creyD/prettier_action@master
        with:
          prettier_options: --write {**/*,*}.{js,jsx,mjs,cjs,ts,tsx,css,scss,sass}
          file_pattern: "src"
          prettier_plugins: "prettier-plugin-tailwindcss"

...
```
my `.prettierrc.js`
```js
/** @type {import("prettier").Options} */
module.exports = {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: true,
  plugins: ['prettier-plugin-tailwindcss'],
};
```
and my `devDependencies`
```json
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "@typescript-eslint/parser": "^5.62.0",
    "eslint": "^8.47.0",
    "eslint-plugin-jest-dom": "^5.0.2",
    "eslint-plugin-react": "^7.33.2",
    "prettier": "^3.0.2",
    "prettier-plugin-tailwindcss": "^0.5.3",
    "tailwindcss": "^3.3.3"
  },
```

**Comment by koppor** [comment]
I can confirm

1. This is not fixed with version 4.3
2. The workaround with `npm install prettier prettier-plugin-java --save-dev` works.

**Comment by creyD** [comment]
@andershagbard @koppor Sorry for the extreme delay. Does this still happen in v4.4? I am quite puzzled how it can happen. Did anyone confirm that actually the other plugin (shopify liquid)  is being installed?

**Comment by andershagbard** [comment]
Still getting the same error. I tried with both Tailwind and Shopify prettier plugin individually, and both failed

**Comment by creyD** [comment]
@andershagbard Thanks for testing again! Unfortunately I still don't know why this happens.

**Comment by andershagbard** [comment]
Could it have something to do with installing the packages using `npm` and running prettier using `npx` ?

**Comment by bjornforsberg** [comment]
Can confirm it works if you add a `yarn install` or `npm i` step before:

```yaml
name: Prettier

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - name: Yarn install
        run: yarn install
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --list-different --write --ignore-unknown "app/**/*.{js,css,scss}"
          prettier_plugins: '@prettier/plugin-ruby @4az/prettier-plugin-html-erb prettier-plugin-tailwindcss'
          only_changed: true
          github_token: ${{ secrets.bundle_token }}
```

## Result:

```
Run yarn install
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 26.56s.
8s
Run creyD/prettier_action@v4.3
Run PATH=$GITHUB_ACTION_PATH/node_modules/.bin:$PATH /home/runner/work/_actions/creyD/prettier_action/v4.3/entrypoint.sh
  
Installing prettier...
Checking plugin: @prettier/plugin-ruby
Checking plugin: @4az/prettier-plugin-html-erb
Checking plugin: prettier-plugin-tailwindcss
Prettifying files...
Files:
Prettier result: 0
Deleting node_modules/ folder...
No package-lock.json file.
Finishing dry-run.
No unpretty files!
Nothing to commit. Exiting.
```
